---
- name: Ansible Playbook to automate installation and updation of operators on OCP
  hosts: localhost
  become: yes
  vars_files:
     - vars.yml
  tasks:
    - name: Unset env variable
      shell: "unset http_proxy; unset https_proxy;"
    - name: Run the index image
      containers.podman.podman_container:
        name: operator-index
        image: "{{ index_image }}:v{{ ocp_version }}"
        state: started
        ports:
           - "50051:50051"
        detach: yes
    - name: Copy the index database inside the container
      shell: podman exec -it operator-index cp /database/index.db /registry/index.db 
      tags:
        - prune
    - name: Prune the database
      command: "podman exec -it operator-index opm registry prune -p {{ var_prune }} --database /registry/index.db"
      tags:
        - prune
    - name: Copy the index database inside the container
      shell: "podman cp operator-index:/registry/index.db ."
      tags:
        - prune
    - name: Copy the index database inside the container
      shell: "podman cp index.db operator-index:/database/index.db"
      tags:
        - prune
- name: Push the index container to mirror registry
  hosts: localhost
  become: yes
  vars_files:
     - vars.yml
  tasks:
    - name: Generate the new image starting from the modified container
      command: "podman commit operator-index {{ local_registry_name }}/olm-mirror/redhat-operator-index:v{{ ocp_version }}"
      when: ocp_version != 4.6
      tags:
        - push
    - name: Generate the new image starting from the modified container (4.6)
      command: "podman commit -f docker operator-index {{ local_registry_name }}/olm-mirror/redhat-operator-index:v{{ ocp_version }}"
      when: ocp_version == 4.6
      tags:
        - push
    - name: Push the new index image in local registry
      command: "podman push {{ local_registry_name }}/olm-mirror/redhat-operator-index:v{{ ocp_version }}"
      tags:
        - push
- name: Mirror the catalog into the disk
  hosts: localhost
  vars_files:
     - vars.yml
  become: yes
  tasks:
    - name: Create temp directory called olmmirror
      file:
        path: "{{ mirror_dest }}/mirror"
        state: directory
      tags:
        - mirror_catalog
    - name: Store the mirrored images into a file called mirror
      command: oc adm catalog mirror {{ local_registry_name }}/olm-mirror/redhat-operator-index:v{{ ocp_version }} file://mirror -a {{ var_credentials_file }} --skip-verification=false --insecure=true
      args:
        chdir: "{{ mirror_dest }}/mirror"
      tags:
        - mirror_catalog
    - name: Tar the file 
      archive:
        path: "{{ mirror_dest }}/mirror/v2"
        dest: "{{ mirror_dest }}/mirror/mirror.tgz"
      tags:
        - mirror_catalog
    - name: Save the mirror catalog image in tar file
      command: "podman save -o {{ mirror_dest }}/index-operator.tar {{ local_registry_name }}/olm-mirror/redhat-operator-index:v{{ ocp_version }}"
- name: Copy the file to remote host and load the catalog
  hosts: localhost
  vars_files:
     - vars.yml
  tasks:
   - name: Create temp directory
     file:
       path: "/tmp/olmmirror_{{ ocp_version }}"
       state: directory
     tags:
       - load
   - name: Copy the archived file to remote host and unarchive
     unarchive:
       src: "{{ mirror_dest }}/mirror/mirror.tgz"
       dest: "/tmp/olmmirror_{{ ocp_version }}"
     tags:
       - load
   - name: Load the catalog into the mirrored registry
     command: "oc adm catalog mirror file://mirror/olm-mirror/redhat-operator-index:v4.7 {{ dest_registry_name }}/olm-mirror -a {{ var_credentials_file }}"
     args:
       chdir: "/tmp/olmmirror_{{ ocp_version }}/v2"
     tags:
       - load
   - name: Copy the catalog mirror to the mirror registry
     copy:
       src: "{{ mirror_dest }}/index-operator.tar"
       dest: "/tmp/"
     tags:
       - load
   - name: Load the podman image to the disconnected mirror registry
     command: podman load -i /tmp/index-operator.tar
     register: podman_index_load
   - name: Push the index operator to the mirror registry
     command: "podman push {{ podman_index_load. }}"
